### ISSUE TITLE
greenodoo 8 突然打不开了

### ISSUE THREAD

**Issue by yanggg1133** [buke/GreenOdoo#25]
greenodoo 8 突然打不开了,css和js 部分加载不了
1.运行odoo大概10天左右 postgresql奔溃了。重新安装了数据库， 我还把addons复制到了openerp里面了。否则编译不了。做不了2此开发
2 css和js 部分加载不了
http://127.0.0.1:8069/web#menu_id=4&action= 就这个页面

日志

2015-03-31 10:57:14,803 7184 ERROR myodoo openerp.service.server: Exception happened during processing of request from ('127.0.0.1', 53038)
Traceback (most recent call last):
  File "D:\GreenOdoo-8.0-win32\runtime\python\lib\SocketServer.py", line 582, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\GreenOdoo-8.0-win32\runtime\python\lib\SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\GreenOdoo-8.0-win32\runtime\python\lib\SocketServer.py", line 640, in **init**
    self.finish()
  File "D:\GreenOdoo-8.0-win32\runtime\python\lib\SocketServer.py", line 693, in finish
    self.wfile.flush()
  File "D:\GreenOdoo-8.0-win32\runtime\python\lib\socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 10053]

**Comment by mrshelly** [comment]
错误 log 中没有关于 PostgreSQL 数据库崩溃的信息... 推荐 贴全 logs
